### PR TITLE
Add possibility to add a custom log

### PR DESCRIPTION
**Pull request by reyostallenberg**
I added the possibility to add a custom log, so for example one can do:

```php
$auditSubscriber = new AuditSubscriber($securityTokenStorage));
$auditSubscriber->log('view', $entity, $em);
```

When the \Doctrine\Common\Persistence\ManagerRegistry would be inserted in AuditSubscriber, the 3rd argument would become obsolete, because the EntityManager can be determined by is in ManagerRegistry->getEntityManagerForClass. This is usable in many of the code of the AuditSubscriber class.

I could do more extraction to separate the logging functionality to a separate class from the AuditSubscriber if you want.

### CODE REVIEW

**Comment by l3pp4rd** [comment]
the whole point of audit subscriber is to use the same transaction within flush to perform audit log in that same transaction. If your application during a request performs more than one transaction or any other db modification without transaction, then you may make your database inconsistent at any moment. I will never allow a library to do or advocate such a thing (this log is not asynchronous)

I suggest you to make a pull request, making all private methods protected (including initPersisters you made). so that you can extend the listener and do whatever works for you.

**Comment by reyostallenberg** [comment]
I don't understand your point of view. What's bad on having the possibility to log other stuff then only doctrine changesets? How will it make your database inconsistent at any moment?

> I suggest you to make a pull request, making all private methods protected (including initPersisters you made). so that you can extend the listener and do whatever works for you.
I don't want to `extend`. I want to log just some custom action I need to log besides all other logging done in this library

**Comment by l3pp4rd** [comment]
Hi, you sure know what transaction is right? something that contains a bulk of actions and it fails or succeeds atomically. if you do a custom log, that will not go together with doctrine changeset transaction and though will not happen atomically within user request. that violates the whole point of this audit logger.

Now if we think, how it could happen within same transaction with doctrine changesets. we could store the custom log in a somewhat temp memory and flush it together with doctrine changesets, but what if there are no doctrine changesets? the listener would never be triggered and your changes would just be lost.

So instead of modifying any code at all and creating custom logs, why you cannot simply, create the AuditLog entry the usual way and persist it like any other Entity. I can accept a pull request, which will add constructor with all properties to this Entity. or just use reflection to create that entity with all needed properties

**Comment by reyostallenberg** [comment]
Who says I want to 'go together with doctrine changeset transaction'. That's not the point, this change is meant to be able log separately. Like user X viewed object Y. How's that a violation of the principle of an audit logger? I think you have created this library with another purpose, but why not serve the purpose I propose?

**Comment by reyostallenberg** [comment]
All right

**Pull request closed without merging**
